#!/usr/bin/env python3

import os, sys
try:
    from lib import Settings
    from lib import CertBase, CertCA, CertServer, CertUser, UserManager
    from wapy.tools import Console, JSONSettings
except ModuleNotFoundError: #pylint: disable=E0602
    print('modules not found, please run "setup.sh"')
    sys.exit()

class CertAdmin:

    def __init__(self):

        scriptName = os.path.realpath(__file__)
        os.chdir(os.path.dirname(scriptName))

        self.settings = Settings()
        try:
            self.settings.load()
        except JSONSettings.SettingsError as e:
            print(e)
            sys.exit()

        self.certCA = CertCA.loadOrCreate(self.settings)

    def creteServer(self):

        certServer = CertServer(self.settings, self.certCA)
        try:
            certServer.load()
            print(Console.magenta('server certificate already exists'))
        except CertBase.LoadError: 
            certServer.create(self.settings.getServerName())
            print(Console.green('created server certificate'))

    def createUser(self, name):

        certUser = CertUser(self.settings, name, self.certCA)
        try:
            certUser.load()
            print(Console.magenta('user certificate already exists'))
        except CertBase.LoadError: 
            certUser.create()
            print(Console.green('created user certificate'))

        self.addUser(name)

    def addUser(self, name):

        try:
            userManager = UserManager(self.settings)
            userManager.add(name)
            print(Console.green('user {0} has now access').format(name))  
        except UserManager.UserError as e:
            print(e)            

    def removeUser(self, name):

        try:
            userManager = UserManager(self.settings)
            userManager.remove(name)
            print(Console.green('user {0} has no longer access').format(name))  
        except UserManager.UserError as e:
            print(e)

    @staticmethod
    def printHelp():
        
        print(Console.blue('certadmin'))
        print(Console.white('* server:') + ' create a server certificate')
        print(Console.white('* create <username>:') + ' create user certificate and grant access')
        print(Console.white('* grant <username>:') + ' grant access for given user')
        print(Console.white('* revoke <username>:') + ' revoke access for given luser')
        print(Console.white('* gui:') + ' show the gui')        

def main():
    
    if len(sys.argv) < 2:    
        CertAdmin.printHelp()
        sys.exit()
    else:  
        command = sys.argv[1]

    if len(sys.argv) > 2:
        argument = sys.argv[2]

    if command == 'server':
        certAdmin = CertAdmin()
        certAdmin.creteServer()
    elif command == 'create':
        certAdmin = CertAdmin()
        certAdmin.createUser(argument)
    elif command == 'grant':
        certAdmin = CertAdmin()
        certAdmin.addUser(argument)
    elif command == 'revoke':
        certAdmin = CertAdmin()
        certAdmin.removeUser(argument)
    elif command == 'gui':
        from lib.gui import startGui
        startGui()
    else:
        CertAdmin.printHelp()

if __name__ == '__main__':
    main()